export const Market = {
    Corn: 1,
    "Wheat": 1,
    "Tomato": 1,
    "Potato": 1,
    "Berry": 1,
    "Strawberry": 1,
    "Pumpkin": 1,
    "Lettuce": 1,
    "Eggplant": 1,
    "Pepper": 1,
    "Broccoli": 1,
    "Cauliflower": 1,
    "Coffee": 1,
    "Beans": 1,
    "Garlic": 1,
    "Grain": 1,
    "Grapes": 1,
    "Persimmon": 1,
    "Pomegranate": 1,
    "Radish": 1,
    "Starfruit": 1,
    "Sweet Potato": 1,
    "Turnip": 1,
    "Camelia": 1,
    "Hydrangea": 1,
    "Lily": 1,
    "Orchid": 1,
    "Poppy": 1,
    "Rose": 1,
};