const resource = [
    {
        name: "Corn",
        source: "/Images/Crops/Corn.png",
        value: 1,
        expiration: 10,
        rarity: "common",
        type: "vegetable",
        color: ["yellow", "green"],
        region: 'Field',
    },
    {
        name: "Wheat",
        source: "/Images/Crops/Wheat.png",
        value: 2,
        expiration: 12,
        rarity: "common",
        type: "grain",
        color: ["gold", "brown"],
        region: 'Field',
    },
    {
        name: "Tomato",
        source: "/Images/Crops/Tomato.png",
        value: 3,
        expiration: 7,
        rarity: "uncommon",
        type: "fruit",
        color: ["red", "green"],
        region: 'Farm',
    },
    {
        name: "Potato",
        source: "/Images/Crops/Potato.png",
        value: 2,
        expiration: 15,
        rarity: "common",
        type: "rhizome",
        color: ["brown", "tan"],
        region: 'Field',
    },
    {
        name: "Berry",
        source: "/Images/Crops/Berry.png",
        value: 1,
        expiration: 14,
        rarity: "common",
        type: "fruit",
        color: ["purple", "red", "blue"],
        region: 'Orchard',
    },
    {
        name: "Strawberry",
        source: "/Images/Crops/Strawberry.png",
        value: 4,
        expiration: 5,
        rarity: "rare",
        type: "fruit",
        color: ["red", "green"],
        region: 'Farm',
    },
    {
        name: "Pumpkin",
        source: "/Images/Crops/Pumpkin.png",
        value: 5,
        expiration: 20,
        rarity: "epic",
        type: "vegetable",
        color: ["orange", "green"],
        region: 'Farm',
    },
        {
        name: "Lettuce",
        source: "/Images/Crops/Lettuce.png",
        value: 2,
        expiration: 6,
        rarity: "uncommon",
        type: "vegetable",
        color: ["green", "light green"],
        region: 'Farm',
    },
    {
        name: "Eggplant",
        source: "/Images/Crops/Eggplant.png",
        value: 2,
        expiration: 18,
        rarity: "uncommon",
        type: "vegetable",
        color: ["purple", "green"],
        region: 'Farm',
    },
    {
        name: "Pepper",
        source: "/Images/Crops/Pepper.png",
        value: 3,
        expiration: 9,
        rarity: "rare",
        type: "vegetable",
        color: ["red", "green", "yellow", "orange"],
        region: 'Farm',
    },
    {
        name: "Broccoli",
        source: "/Images/Crops/Broccoli.png",
        value: 3,
        expiration: 8,
        rarity: "uncommon",
        type: "vegetable",
        color: ["green", "dark green"],
        region: 'Farm',
    },
    {
        name: "Cauliflower",
        source: "/Images/Crops/Cauliflower.png",
        value: 4,
        expiration: 9,
        rarity: "rare",
        type: "vegetable",
        color: ["white", "green"],
        region: 'Farm',
    },
    {
        name: "Coffee",
        source: "/Images/Crops/Coffee.png",
        value: 5,
        expiration: 30,
        rarity: "epic",
        type: "fruit",
        color: ["brown", "green", "red"],
        region: 'Farm',
    },
        {
        name: "Beans",
        source: "/Images/Crops/Beans.png",
        value: 2,
        expiration: 12,
        rarity: "common",
        type: "vegetable",
        color: ["green", "brown", "purple"],
        region: 'Orchard',
    },
    {
        name: "Garlic",
        source: "/Images/Crops/Garlic.png",
        value: 3,
        expiration: 18,
        rarity: "uncommon",
        type: "rhizome",
        color: ["white", "purple"],
        region: 'Field',
    },
    {
        name: "Grain",
        source: "/Images/Crops/Grain.png",
        value: 2,
        expiration: 20,
        rarity: "common",
        type: "grain",
        color: ["gold", "yellow"],
        region: 'Field',
    },
    {
        name: "Grapes",
        source: "/Images/Crops/Grapes.png",
        value: 4,
        expiration: 6,
        rarity: "rare",
        type: "fruit",
        color: ["purple", "green", "red"],
        region: 'Orchard',
    },
    {
        name: "Persimmon",
        source: "/Images/Crops/Persimmon.png",
        value: 5,
        expiration: 10,
        rarity: "epic",
        type: "fruit",
        color: ["orange", "green"],
        region: 'Orchard',
    },
    {
        name: "Pomegranate",
        source: "/Images/Crops/Pomegranate.png",
        value: 5,
        expiration: 12,
        rarity: "epic",
        type: "fruit",
        color: ["red", "pink", "green"],
        region: 'Orchard',
    },
    {
        name: "Radish",
        source: "/Images/Crops/Radish.png",
        value: 2,
        expiration: 10,
        rarity: "uncommon",
        type: "rhizome",
        color: ["red", "white", "green"],
        region: 'Field',
    },
    {
        name: "Starfruit",
        source: "/Images/Crops/Starfruit.png",
        value: 6,
        expiration: 7,
        rarity: "legendary",
        type: "fruit",
        color: ["yellow", "green"],
        region: 'Orchard',
    },
        {
        name: "Sweet Potato",
        source: "/Images/Crops/SweetPotato.png",
        value: 3,
        expiration: 15,
        rarity: "uncommon",
        type: "rhizome",
        color: ["purple", "orange"],
        region: 'Field',
    },
    {
        name: "Turnip",
        source: "/Images/Crops/Turnip.png",
        value: 2,
        expiration: 13,
        rarity: "common",
        type: "rhizome",
        color: ["white", "purple", "green"],
        region: 'Farm',
    },
    {
        name: "Camelia",
        source: "/Images/Crops/Camelia.png",
        value: 4,
        expiration: 8,
        rarity: "rare",
        type: "flower",
        color: ["pink", "red", "white"],
        region: 'Garden',
    },
    {
        name: "Hydrangea",
        source: "/Images/Crops/Hydrangea.png",
        value: 3,
        expiration: 7,
        rarity: "uncommon",
        type: "flower",
        color: ["blue", "purple", "pink"],
        region: 'Garden',
    },
    {
        name: "Lily",
        source: "/Images/Crops/Lily.png",
        value: 4,
        expiration: 6,
        rarity: "rare",
        type: "flower",
        color: ["white", "yellow", "pink"],
        region: 'Garden',
    },
    {
        name: "Orchid",
        source: "/Images/Crops/Orchid.png",
        value: 5,
        expiration: 9,
        rarity: "epic",
        type: "flower",
        color: ["purple", "white", "pink"],
        region: 'Garden',
    },
    {
        name: "Poppy",
        source: "/Images/Crops/Poppy.png",
        value: 3,
        expiration: 5,
        rarity: "uncommon",
        type: "flower",
        color: ["red", "orange", "pink"],
        region: 'Garden',
    },
    {
        name: "Rose",
        source: "/Images/Crops/Rose.png",
        value: 5,
        expiration: 10,
        rarity: "epic",
        type: "flower",
        color: ["red", "pink", "white", "yellow"],
        region: 'Garden',
    }
]

export const resources = (max = 99)=>{
    let res = [];
    res = resource.map((r)=>({
        ...r,
        quantity: 0,
        value: Math.floor(Math.random() * 10) + 1
    }))
    let res2 = [];
    let ctr = 0;
    res.forEach(r => {
        ctr += 1;
        if(ctr <= max){
            res2.push(r);
        }
    })
    return res2;
}
